---
apiVersion: spanner.mercari.com/v1alpha1
kind: SpannerAutoscaler
metadata:
  name: spannerautoscaler-sample
  namespace: test
spec:
  scaleTargetRef:
    projectId: test-project
    instanceId: test-instance
  serviceAccountSecretRef:
    name: spanner-autoscaler-gcp-sa
    key: service-account
  minNodes: 1
  maxNodes: 4
  maxScaleDownNodes: 2
  targetCPUUtilization:
    highPriority: 80
