---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spanner-autoscaller-service-account-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
    resourceNames: ["spanner-autoscaler-service-account"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spanner-autoscaller-service-account-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spanner-autoscaller-service-account-reader
subjects:
  - kind: ServiceAccount
    name: spanner-autoscaler-controller-manager
    namespace: spanner-autoscaler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spanner-autoscaller-event-publisher
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spanner-autoscaller-event-publisher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spanner-autoscaller-event-publisher
subjects:
  - kind: ServiceAccount
    name: spanner-autoscaler-controller-manager
    namespace: spanner-autoscaler
